### ISSUE TITLE
notebook and access to dataset from Ftp

### ISSUE THREAD

**Issue by JulienMaille** [skokec/segdec-net-jim2019#5]
hello, it looks like we can't access the ftp described in your readme anymore
ftp://box.vicos.si/skokec/gostop/KolektorSDD-training-splits.zip

I tried to setup a Google Colab notebook running your code but can't get it to properly work.
https://colab.research.google.com/drive/1IBBZ16sofcZovMh1xNGHmlkF6MBOnBOh#scrollTo=eL6gHlGqXsFL

**Comment by skokec** [comment]
Hi, we have recently moved all the links from ftp to the http. Please use the http versions: 
[http://box.vicos.si/skokec/gostop/KolektorSDD-training-splits.zip](http://box.vicos.si/skokec/gostop/KolektorSDD-training-splits.zip)
